# Generated by Django 4.2.2 on 2023-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_user_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
