# Generated by Django 4.2.2 on 2023-06-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_user_detail_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
