# Generated by Django 4.2.2 on 2023-06-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_user_detail_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('start_Date', models.DateField()),
                ('end_Date', models.DateField()),
                ('total_participants', models.CharField(max_length=100)),
                ('remaining_participants', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(blank=True, max_length=20)),
                ('updated_date', models.DateTimeField(blank=True, max_length=20)),
                ('organizer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.user_detail')),
            ],
        ),
    ]
