# Generated by Django 4.2.2 on 2023-06-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_create_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_event',
            name='remaining_participants',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
