# Generated by Django 4.2.2 on 2023-06-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_alter_create_event_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_event',
            name='remaining_participants',
        ),
        migrations.AddField(
            model_name='create_event',
            name='ending_time',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='create_event',
            name='starting_time',
            field=models.TimeField(max_length=100, null=True),
        ),
    ]
