# Generated by Django 4.2.2 on 2023-06-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_remove_create_event_remaining_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_event',
            name='ending_time',
            field=models.TimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='create_event',
            name='starting_time',
            field=models.TimeField(max_length=100),
        ),
    ]
