# Generated by Django 4.2.2 on 2023-06-20 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0015_rename_remaining_participants_create_event_registered_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, max_length=20)),
                ('updated_date', models.DateTimeField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=1)),
                ('updated_By_id', models.CharField(blank=True, max_length=100)),
                ('deleted_By_id', models.CharField(blank=True, max_length=100)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.create_event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.user_detail')),
            ],
        ),
    ]
